// <auto-generated />
using System;
using Logix.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logix.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230606135928_InitMgt")]
    partial class InitMgt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Logix.Domain.ACC.AccAccount", b =>
                {
                    b.Property<long>("AccAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Acc_Account_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccAccountId"), 1L, 1);

                    b.Property<string>("AccAccountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Acc_Account_Code");

                    b.Property<string>("AccAccountName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Acc_Account_Name");

                    b.Property<string>("AccAccountName2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Acc_Account_Name2");

                    b.Property<string>("AccAccountParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Acc_Account_Parent_Code");

                    b.Property<long?>("AccAccountParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("Acc_Account_Parent_ID");

                    b.Property<long?>("AccAccountParentId2")
                        .HasColumnType("bigint")
                        .HasColumnName("Acc_Account_Parent_ID2");

                    b.Property<long?>("AccAccountParentId3")
                        .HasColumnType("bigint")
                        .HasColumnName("Acc_Account_Parent_ID3");

                    b.Property<long?>("AccGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("Acc_group_ID");

                    b.Property<int?>("AccountCloseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Account_Close_type_ID");

                    b.Property<int?>("AccountLevel")
                        .HasColumnType("int")
                        .HasColumnName("Account_level");

                    b.Property<bool?>("Aggregate")
                        .HasColumnType("bit")
                        .HasColumnName("aggregate");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_ID");

                    b.Property<long?>("CcId")
                        .HasColumnType("bigint")
                        .HasColumnName("CC_ID")
                        .HasComment("مركز التكلفة الافتراضي");

                    b.Property<int?>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Currency_ID")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Delete_Date");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int")
                        .HasColumnName("Delete_User_ID");

                    b.Property<long?>("FacilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Facility_ID");

                    b.Property<bool?>("FlagDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Insert_Date");

                    b.Property<int?>("InsertUserId")
                        .HasColumnType("int")
                        .HasColumnName("Insert_User_ID");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsHelpAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("Is_Help_Account")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsSub")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Sub");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_Date");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("Update_User_ID");

                    b.HasKey("AccAccountId");

                    b.HasIndex(new[] { "AccAccountCode", "FlagDelete", "FacilityId" }, "Acc_Code")
                        .IsUnique()
                        .HasFilter("([FlagDelete]=(0))");

                    b.HasIndex(new[] { "AccAccountParentId" }, "Index_Parent_ID");

                    b.ToTable("ACC_Accounts");
                });

            modelBuilder.Entity("Logix.Domain.HR.HrEmployee", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Account_Code");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("Account_ID");

                    b.Property<string>("AccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Account_No");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressCountry")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Address_Country");

                    b.Property<int?>("AnnualIncreaseMethod")
                        .HasColumnType("int");

                    b.Property<bool?>("ApplySalaryLadder")
                        .HasColumnType("bit")
                        .HasColumnName("Apply_Salary_ladder");

                    b.Property<int?>("AttendanceType")
                        .HasColumnType("int")
                        .HasColumnName("Attendance_Type");

                    b.Property<int?>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("Bank_ID");

                    b.Property<string>("BirthDate")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Birth_Place");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BRANCH_ID");

                    b.Property<long?>("ById")
                        .HasColumnType("bigint")
                        .HasColumnName("By_ID");

                    b.Property<string>("CardExpirationDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Card_Expiration_Date");

                    b.Property<long?>("CcId")
                        .HasColumnType("bigint")
                        .HasColumnName("CC_ID");

                    b.Property<bool?>("CheckDevice")
                        .HasColumnType("bit")
                        .HasColumnName("Check_Device");

                    b.Property<bool?>("CheckDeviceActive")
                        .HasColumnType("bit")
                        .HasColumnName("Check_Device_Active");

                    b.Property<int?>("ChequeCash")
                        .HasColumnType("int")
                        .HasColumnName("Cheque_Cash");

                    b.Property<string>("ContarctDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Contarct_Date");

                    b.Property<string>("ContractData")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Contract_Data");

                    b.Property<string>("ContractExpiryDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Contract_expiry_Date");

                    b.Property<int?>("ContractTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Contract_Type_ID");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DailyWorkingHours")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Daily_Working_hours");

                    b.Property<int?>("DegreeId")
                        .HasColumnType("int")
                        .HasColumnName("Degree_ID");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_ID");

                    b.Property<bool?>("DirectDeposit")
                        .HasColumnType("bit")
                        .HasColumnName("Direct_Deposit");

                    b.Property<string>("Doappointment")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("DOAppointment");

                    b.Property<string>("Doappointmentold")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DOAppointmentold");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpCode2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Emp_Code2");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Emp_ID");

                    b.Property<string>("EmpName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Emp_name");

                    b.Property<string>("EmpName2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Emp_name2");

                    b.Property<string>("EmpPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Emp_Photo");

                    b.Property<string>("EntryDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Entry_Date");

                    b.Property<string>("EntryNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Entry_NO");

                    b.Property<string>("EntryPort")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Entry_Port");

                    b.Property<bool?>("ExcludeAttend")
                        .HasColumnType("bit")
                        .HasColumnName("Exclude_Attend");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("Facility_ID");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GoisSubscriptionExpiryDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gois_Subscription_Expiry_Date");

                    b.Property<decimal?>("GosiAllowanceCommission")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gosi_Allowance_Commission");

                    b.Property<decimal?>("GosiBiscSalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gosi_Bisc_Salary");

                    b.Property<string>("GosiDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gosi_Date");

                    b.Property<decimal?>("GosiHouseAllowance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gosi_House_Allowance");

                    b.Property<string>("GosiNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Gosi_No");

                    b.Property<decimal?>("GosiOtherAllowances")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gosi_Other_Allowances");

                    b.Property<decimal?>("GosiRateFacility")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gosi_Rate_Facility");

                    b.Property<decimal?>("GosiSalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gosi_Salary");

                    b.Property<int?>("GosiType")
                        .HasColumnType("int")
                        .HasColumnName("Gosi_Type");

                    b.Property<bool?>("HaveBankLoan")
                        .HasColumnType("bit")
                        .HasColumnName("Have_Bank_Loan");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Home_Phone");

                    b.Property<decimal?>("HourCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Hour_Cost");

                    b.Property<string>("Iban")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IBAN");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("IdExpireDate")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID_Expire_Date");

                    b.Property<string>("IdIssuer")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ID_Issuer");

                    b.Property<string>("IdIssuerDate")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID_Issuer_Date");

                    b.Property<string>("IdNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID_No");

                    b.Property<int?>("IdType")
                        .HasColumnType("int")
                        .HasColumnName("ID_Type");

                    b.Property<string>("InsuranceCardNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Insurance_Card_No");

                    b.Property<int?>("InsuranceCategory")
                        .HasColumnType("int")
                        .HasColumnName("Insurance_Category");

                    b.Property<int?>("InsuranceCompany")
                        .HasColumnType("int")
                        .HasColumnName("Insurance_Company");

                    b.Property<string>("InsuranceDateValidity")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Insurance_Date_Validity");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSub")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Sub");

                    b.Property<bool?>("IsTicket")
                        .HasColumnType("bit")
                        .HasColumnName("IS_Ticket");

                    b.Property<bool?>("Isdel")
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL");

                    b.Property<int?>("JobCatagoriesId")
                        .HasColumnType("int")
                        .HasColumnName("Job_Catagories_ID");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Job_Description");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("Job_ID");

                    b.Property<int?>("JobType")
                        .HasColumnType("int")
                        .HasColumnName("Job_Type");

                    b.Property<string>("KeyCheckDevice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Key_Check_Device");

                    b.Property<string>("LastIncrementDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastPromotionDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("Level_ID");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<long?>("Manager2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("Manager2_ID");

                    b.Property<long?>("Manager3Id")
                        .HasColumnType("bigint")
                        .HasColumnName("Manager3_ID");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("Manager_ID");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("int")
                        .HasColumnName("Marital_Status");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int")
                        .HasColumnName("Nationality_ID");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteContract")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note_Contract");

                    b.Property<string>("OccupationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Occupation_ID");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Office_Phone");

                    b.Property<string>("OfficePhoneEx")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Office_Phone_Ex");

                    b.Property<string>("OthersRequirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Others_Requirements");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("Parent_ID");

                    b.Property<string>("PassExpireDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pass_Expire_Date");

                    b.Property<string>("PassIssuer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pass_Issuer");

                    b.Property<string>("PassIssuerDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pass_Issuer_Date");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Passport_No");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Payment_Type_ID");

                    b.Property<int?>("PayrollType")
                        .HasColumnType("int")
                        .HasColumnName("Payroll_Type");

                    b.Property<string>("PhoneCountry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Phone_Country");

                    b.Property<int?>("PlaceAttendance")
                        .HasColumnType("int")
                        .HasColumnName("Place_Attendance");

                    b.Property<string>("Pobox")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("POBox");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Postal_Code");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int")
                        .HasColumnName("Program_ID");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("int")
                        .HasColumnName("Qualification_ID");

                    b.Property<string>("ReasonStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reason_Status");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int")
                        .HasColumnName("Religion_ID");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SalaryGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("Salary_Group_ID");

                    b.Property<bool?>("ShareContactInfo")
                        .HasColumnType("bit")
                        .HasColumnName("Share_ContactInfo");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int")
                        .HasColumnName("Specialization_ID");

                    b.Property<int?>("SponsorsId")
                        .HasColumnType("int")
                        .HasColumnName("Sponsors_ID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("Status_ID");

                    b.Property<string>("StopDateSalary")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Stop_Date_Salary");

                    b.Property<bool?>("StopSalary")
                        .HasColumnType("bit")
                        .HasColumnName("Stop_salary");

                    b.Property<int?>("StopSalaryCode")
                        .HasColumnType("int")
                        .HasColumnName("Stop_Salary_Code");

                    b.Property<int?>("TicketEntitlement")
                        .HasColumnType("int")
                        .HasColumnName("Ticket_Entitlement");

                    b.Property<string>("TicketNoDependent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ticket_No_Dependent");

                    b.Property<string>("TicketTo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Ticket_to");

                    b.Property<int?>("TicketType")
                        .HasColumnType("int")
                        .HasColumnName("Ticket_Type");

                    b.Property<string>("TrialExpiryDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Trial_Expiry_Date");

                    b.Property<int?>("TrialStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Trial_Status_ID");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.Property<decimal?>("Vacation2DaysYear")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Vacation2_Days_Year");

                    b.Property<int?>("VacationDaysYear")
                        .HasColumnType("int")
                        .HasColumnName("Vacation_Days_Year");

                    b.Property<decimal?>("ValueTicket")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value_Ticket");

                    b.Property<string>("VisaNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Visa_No");

                    b.Property<int?>("WagesProtection")
                        .HasColumnType("int")
                        .HasColumnName("Wages_Protection");

                    b.Property<string>("WorkDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Work_Date");

                    b.Property<string>("WorkExpDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Work_ExpDate");

                    b.Property<string>("WorkNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Work_No");

                    b.Property<string>("WorkPlace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Work_Place");

                    b.ToView("HR_Employee");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysAnnouncement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AttachFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Attach_File");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("Branch_ID");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_ID");

                    b.Property<int?>("DeptLocationId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Location_ID");

                    b.Property<string>("Detailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("End_Date");

                    b.Property<long?>("FacilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Facility_ID");

                    b.Property<string>("GroupsId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Groups_ID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Language")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("Location_ID");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("PublishDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Publish_Date");

                    b.Property<string>("StartDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Start_Date");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Users_ID");

                    b.HasKey("Id");

                    b.ToTable("Sys_Announcement");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysAnnouncementLocationVw", b =>
                {
                    b.Property<int?>("CatagoriesId")
                        .HasColumnType("int")
                        .HasColumnName("Catagories_ID");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<bool?>("Isdel")
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Location_Name");

                    b.Property<int?>("SortNo")
                        .HasColumnType("int")
                        .HasColumnName("Sort_no");

                    b.ToView("Sys_Announcement_Location_VW");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysAnnouncementVw", b =>
                {
                    b.Property<string>("AttachFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Attach_File");

                    b.Property<string>("BraName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BRA_NAME");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("Branch_ID");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Department_Name");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_ID");

                    b.Property<int?>("DeptLocationId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Location_ID");

                    b.Property<string>("DeptLocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Dept_Location_Name");

                    b.Property<string>("Detailes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("End_Date");

                    b.Property<long?>("FacilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Facility_ID");

                    b.Property<string>("GroupsId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Groups_ID");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Language")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("Location_ID");

                    b.Property<string>("LocationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Location_Name");

                    b.Property<string>("PublishDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Publish_Date");

                    b.Property<string>("StartDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Start_Date");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Type_Name");

                    b.Property<string>("UserFullname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_FULLNAME");

                    b.Property<string>("UsersId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Users_ID");

                    b.ToView("Sys_Announcement_VW");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int?>("CatId")
                        .HasColumnType("int")
                        .HasColumnName("Cat_ID");

                    b.Property<long?>("CcId")
                        .HasColumnType("bigint")
                        .HasColumnName("CC_ID");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("City_ID");

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<long?>("DepMangerId")
                        .HasColumnType("bigint")
                        .HasColumnName("Dep_Manger_ID");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("FacilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Facility_ID");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsShare")
                        .HasColumnType("bit");

                    b.Property<int?>("Isdel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("LevelNo")
                        .HasColumnType("int")
                        .HasColumnName("Level_No");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("Parent_Id");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("Project_ID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("Status_ID");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("Type_ID");

                    b.HasKey("Id");

                    b.ToTable("Sys_Department");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysLookupCategory", b =>
                {
                    b.Property<int>("CatagoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Catagories_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatagoriesId"), 1L, 1);

                    b.Property<string>("CatagoriesName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Catagories_Name");

                    b.Property<string>("CatagoriesName2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Catagories_name2");

                    b.Property<bool?>("IsDeletable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool?>("Isdel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("SystemId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("System_ID");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("CatagoriesId");

                    b.ToTable("Sys_LookUp_Catagories");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysLookupData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("AccAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("Acc_Account_ID");

                    b.Property<int?>("CatagoriesId")
                        .HasColumnType("int")
                        .HasColumnName("Catagories_ID");

                    b.Property<long?>("CcId")
                        .HasColumnType("bigint")
                        .HasColumnName("CC_ID");

                    b.Property<long?>("Code")
                        .HasColumnType("bigint");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("Color_ID");

                    b.Property<string>("Icon")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("Isdel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefranceNo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Refrance_No");

                    b.Property<int?>("SortNo")
                        .HasColumnType("int")
                        .HasColumnName("Sort_no");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code", "CatagoriesId", "Isdel" }, "Ind_catagory")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL AND [Catagories_ID] IS NOT NULL AND [ISDEL] IS NOT NULL");

                    b.ToTable("Sys_lookup_Data");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysScreen", b =>
                {
                    b.Property<long>("ScreenId")
                        .HasColumnType("bigint")
                        .HasColumnName("SCREEN_ID");

                    b.Property<string>("ColorCss")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("Color_Css");

                    b.Property<string>("IconCss")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Icon_Css");

                    b.Property<bool?>("Isdel")
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("Parent_Id");

                    b.Property<string>("ScreenName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SCREEN_NAME");

                    b.Property<string>("ScreenName2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SCREEN_NAME2");

                    b.Property<string>("ScreenUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SCREEN_URL");

                    b.Property<int?>("SortNo")
                        .HasColumnType("int")
                        .HasColumnName("Sort_no");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("System_Id");

                    b.HasKey("ScreenId")
                        .HasName("PK_Sys_SCREEN");

                    b.ToTable("Sys_Screen");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysSystem", b =>
                {
                    b.Property<int>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("System_Id");

                    b.Property<string>("ColorCss")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("Color_Css");

                    b.Property<string>("DefaultPage")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("Default_Page");

                    b.Property<string>("Desc1")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("Desc_1");

                    b.Property<string>("Desc2")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("Desc_2");

                    b.Property<string>("Folder")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconCss")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Icon_Css");

                    b.Property<bool?>("Isdel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Short_Name");

                    b.Property<string>("ShortName2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Short_Name2");

                    b.Property<bool?>("ShowInHome")
                        .HasColumnType("bit")
                        .HasColumnName("Show_In_Home");

                    b.Property<int?>("SysSort")
                        .HasColumnType("int")
                        .HasColumnName("Sys_Sort");

                    b.Property<string>("SystemName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("System_Name");

                    b.Property<string>("SystemName2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("System_Name2");

                    b.HasKey("SystemId");

                    b.ToTable("Sys_System");
                });

            modelBuilder.Entity("Logix.Domain.Main.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AccTransfer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACC_Transfer");

                    b.Property<string>("BranchsId")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("BRANCHS_ID");

                    b.Property<long?>("CandId")
                        .HasColumnType("bigint")
                        .HasColumnName("Cand_ID");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ConnectionID");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("CusId")
                        .HasColumnType("bigint")
                        .HasColumnName("Cus_ID");

                    b.Property<string>("DashboardWidget")
                        .HasMaxLength(2555)
                        .HasColumnType("nvarchar(2555)")
                        .HasColumnName("Dashboard_Widget");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("Emp_ID");

                    b.Property<int?>("Enable")
                        .HasColumnType("int");

                    b.Property<long?>("FacilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Facility_ID");

                    b.Property<string>("GroupsId")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)")
                        .HasColumnName("Groups_ID");

                    b.Property<string>("Ips")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IPS");

                    b.Property<bool?>("IsAgree")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("Isdel")
                        .HasColumnType("bit")
                        .HasColumnName("ISDEL");

                    b.Property<bool?>("Isupdate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Otp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OTP");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("OTP_Expiry");

                    b.Property<string>("ProjectsId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Projects_ID");

                    b.Property<int?>("SalesType")
                        .HasColumnType("int")
                        .HasColumnName("Sales_Type");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SsoToken")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SSO_Token");

                    b.Property<DateTime?>("SsoTokenExpiryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("SSO_Token_Expiry_Date");

                    b.Property<long?>("SupId")
                        .HasColumnType("bigint")
                        .HasColumnName("Sup_ID");

                    b.Property<TimeSpan?>("TimeFrom")
                        .HasColumnType("time")
                        .HasColumnName("Time_From");

                    b.Property<TimeSpan?>("TimeTo")
                        .HasColumnType("time")
                        .HasColumnName("Time_To");

                    b.Property<bool?>("TwoFactor")
                        .HasColumnType("bit")
                        .HasColumnName("Two_factor");

                    b.Property<int?>("TwoFactorType")
                        .HasColumnType("int")
                        .HasColumnName("Two_factor_Type");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_EMAIL");

                    b.Property<string>("UserFullname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_FULLNAME");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<byte[]>("UserPassword")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("USER_PASSWORD");

                    b.Property<string>("UserPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("User_Photo");

                    b.Property<long?>("UserPkId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_PK_ID");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("USER_TYPE_ID");

                    b.Property<string>("WhTransactionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Wh_Transaction_Type");

                    b.HasKey("Id");

                    b.ToTable("SYS_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
